# Generated by Django 4.0.6 on 2022-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('telphone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(default=0.00028260562385191464, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='registered_by',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
